# -*- coding: utf-8 -*-
"""new_py_asignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fLmVMKwl65xlad_hIcnrWSkjUD_S6CI
"""

# Asignment 3 - 

# 1. Learn about in built functions of Python objects 

# a. List 
# b. Dict
# c. Tuple
# d. Set
# e. String

#list

list=[4,5,3,2,1,10]

list

type(list)

#max in the list
max(list)

#sort list
list.sort()

list

#length of the list or count
len(list)

#copy the list to list2
list2=list.copy()
list2

#pop the list
list.pop(-2)
list

#append the list
list.append(5)
list

##dict
car = {
  "brand": "Ford",
  "model": "Endeavour Titanium",
  "year": 1996
}
print(car)
type(car)

#default values to the dict the color
car.setdefault("color", "black")
car

#update the dict && display the values
car.update({"model":"Ford Mustang"})
car.values()

#delete the values in dict
car.pop("year")
car

#clear everthing in dict
car.clear()
car

##tuples
mytuple = ( "banana", "cherry","gakfrute","orange","apple")
print(mytuple)
type(mytuple)

#access he tuple
print(mytuple[1])
print(mytuple[1:3])

#finding the apple in the tuple or not
if "apple" in mytuple:
  print("Yes, 'apple' is in the fruits tuple")

#assign the value to equal tupele 
( yellow, red,green,orange,lightred) = mytuple

print(green)
print(yellow)
print(red)

#Set
mySet = {"apple", "banana", "cherry"}

print(mySet)

#type
type(mySet)

#display the set
for x in mySet:
  print(x)

#diferent style of print
print("gakefrute" in mySet)#out of the set
print("apple" in mySet)# in the set

#add the data to the set
mySet.add("orange")
mySet

#list add to the set in duplication is not allowed
mylist = ["kiwi", "gova"]

mySet.update(mylist)
mySet

#remove the set item
mySet.remove("gova")
mySet

#string

b = "Hello, World!"
print(b[2:5])

#replace the charecters
print(b.replace("H", "J"))

#spliting
print(b.split(","))