# -*- coding: utf-8 -*-
"""new_py_asignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13pta2c21US_V8vFXirKgu-X3RfYiKyZH
"""

# Assignment - 2

# get random names of the people in the list using For loop, Maxmium participant variable and input() function
# and then get your lottery run

import random

participatsList = []
maxTicketsAvalibale = int(input("Enter the Max Avalibale Tickets for lottery "))

for i in range(0, maxTicketsAvalibale):
    print("Enter ", i+1," name")
    names = input()
    participatsList.append(names)
luckyNumber = random.randint(0,maxTicketsAvalibale-1)
print("\n congratulations Mr or Miss :",participatsList[luckyNumber])

