# -*- coding: utf-8 -*-
"""new_py_asignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bZMguO5zh8FjCgAsCUKgJe50hEvBf7v
"""

#asignment 1 Day 4 -

#You all are pilots, you have to land a plane, the altitude required for landing a plane is 1000ft, if it is less than that tell pilot to land the plane, or it is more than that but less than 5000ft ask the pilot to “come down to 1000ft”, else if it is more than 5000ft ask the pilot to “go around and try later”

#Example : Input - 1000 Output - Safe to land

#Example : Input - 4500 Output - Bring down to 1000

#Example : Input - 6500 Output - Turn Around

pilotsHight = 200

while pilotsHight :
  if pilotsHight == "1000" :
    print("Safe to land")
    break
  elif pilotsHight == "4500" :
    print("Bring down to 1000")
  elif pilotsHight == "6500" :
    print("Turn Around")
  else :
    print("Flying")
 
  pilotsHight = input("pilots whats the hight ? - ")