# -*- coding: utf-8 -*-
"""new_py_asignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Q32O1YdTajph_T7S6M6BAQmlGGodFiX
"""

#assignment1
#reading input from user
firstInput = int(input("enter a first number:"))
secondInput = int(input("enter a senconde number:"))
#logic for calulator
sumOfAddition = firstInput + secondInput
sumOfSubstraction = firstInput - secondInput
sumOfMulitiplication = firstInput * secondInput
sumOfDivision = firstInput / secondInput
#printing 
print("Addition of first and second numbers:",sumOfAddition)
print("substraction of first and second numbers:",sumOfSubstraction)
print("mulitiplication of first and second numbers:",sumOfMulitiplication)
print("division of first and second numbers:",sumOfDivision)